noripyt/django-cachalot

cachalot/tests/migrations/0002_auto_20150416_0933.py, cachalot/tests/models.py, cachalot/tests/write.py
Hi Bertrand,
I was experimenting with using cachalot on a big django project that we have. It looks great. 
I came across a problem highlighted by a unit test fail in our project when I had cachalot installed which I think relates to the use of exclude queries with many-to-many related models. I believe the cache is being used when in fact it shouldn't be. I have written a couple of unit tests in write.py (test_clear_with_filters and test_clear_with_excludes) which basically test for the same thing but in one case using .filter() queries (which works fine) and in the other case using .exclude() queries (the tests fail). Note that the failing tests can be made to pass by explicitly calling hub.save() after line 884. I'm not sure what the underlying cause is - it might well be something …
=> Tests related to many to many relationships used via exclude queries

cachalot/panels.py
In Django 1.7 new [app-loading system](https://docs.djangoproject.com/en/1.7/releases/1.7/#app-loading-refactor) was introduced. The old way is deprecated and produces warning in Django 1.8:
````
.../lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
return f(*args, **kwds)
````
=> Switched to new application loading system

cachalot/apps.py, settings.py
This is the new name in 1.9, and the old django.db.backends.postgresql_psycopg2
is left in for backwards compatibility.
Docs on this available [here](https://docs.djangoproject.com/en/1.9/releases/1.9/#database-backends).
=> Add support for django.db.backends.postgresql engine

cachalot/monkey_patch.py
This is a fix for issue #50. Essentially just checks the ```sql``` object and if it is not a unicode object, it will encode it into a unicode object. This fix allows for better backwards compatibility with Python2.7 code, where objects of Type str are encoded in ascii.
=> Unicode encode fix

CHANGELOG.rst, benchmark/conditions.rst, cachalot/__init__.py, cachalot/panels.py
Fixes cache issue in CachalotPanel described in the gitter.im lobby.
=> Fixes cache in CachalotPanel, Version 1.4.2

cachalot/utils.py
Since Django 1.11 the ``query`` argument of the SQLCompiler constructor has always a ``subquery`` property, in fact if the SQL query has no real sub query it is set to False.
As a result, the test done by Django-cachalot in the ``_get_tables`` function is no more accurate and cause a dramatic slow down on 1.11 django installs.
This fix should be backwards compatible with older versions of Django.
=> Fixed django>=1.11 support.

cachalot/settings.py
This patch adds support for MySQL, PostgreSQL and SQLite3 engines wrapped for use with django-prometheus (https://github.com/korfuri/django-prometheus).
It simply adds those engines into the list of supported ones.
I added Prometheus support into my Django project and was scratching my head for quite some time to find out why django-cachalot stopped working. This patch fixes it for me and potentially other users.
=> add django-prometheus wrapped database engines to the list of supported db engines

cachalot/monkey_patch.py
Import ABC from collections.abc
Fixes #159 and improves Python 3 compatibility.
=> Fix warning regarding ABC import from collections

cachalot/api.py, cachalot/monkey_patch.py, cachalot/tests/read.py
This context manager allows for disabling cachalot using a context manager
Description:
Context manager for temporarily disabling cachalot. If you evaluate the same queryset a second time, like normally for Django querysets, this will access the variable that saved it in-memory.
For example:
qs = Test.objects.filter(blah=blah)
with cachalot_disabled():
list(qs)  # Evaluates queryset
list(qs)
list(Test.objects.filter(blah=blah))
It's not time to write some async context manager, but because some people, like me, who use ASGI a lot for websockets, I've defaulted threading.local to asgiref.local.Local if asgiref is available (yes if Django 3.0, but because Django 2.2 is LTS, there must be this try except).
As @beda42 said:
> Sometimes the programmer knows that a query will return a large …
=> Add support for disabling cachalot

cachalot/utils.py
This is to address issue #156 , I've tested this on our code base and it looks to work, where it was rasing exceptions before. Currently with this change it will just ignore subquieries. You might want to improve on this, but this is better than the error before.
Stop a unexpected Exception been raised.
=> Attempt to fix issue #156 by handling subquieries

cachalot/apps.py
To fix issue #125, copyreg can be used to define how memoryview objects should be pickled. 
This allows caching of fields like LineStringField and other GIS-fields and prevents crashes with "Can't pickle memoryview objects".
=> Cast memoryview objects to bytes to be able to pickle them.

cachalot/signals.py
When running a project with this package as dependency, I'm getting the following warning message.
```
RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
```
By moving the argument to a comment it will not pollute the logs when developing in other projects.
=> Remove deprecated argument

CHANGELOG.rst, cachalot/monkey_patch.py
This PR fixes the issue described in #120 by catching KeyErrors on cache retrieval after restarts.
=> Do not throw exception on externally invalidated cache keys

cachalot/api.py
cachalot_disabled is not working.
unused varialbe LOCAL_STORAGE.enabled was configured
instead of LOCAL_STORAGE.cachalot_enabled which is later used
to turn off the caching
=> Fix cachalot_disabled

CHANGELOG.rst, cachalot/settings.py, cachalot/tests/settings.py, docs/quickstart.rst
Fixes #186
Makes adding an entire app more convenient.
Caveat: someone like Reddit has a table like "subreddit_23k2d" as in the last 5 letters give an identification number. This is... not very Django like thus it does not satisfy the wildcard notation that was initially mentioned in the issue. Someone else can monkey patch the functions from https://github.com/noripyt/django-cachalot/blob/1569ff75f0511d7267c28cbdac218968d39107a3/cachalot/utils.py#L158-L177 to include any sort of wildcard functionality. The reason I didn't implement a wildcard functionality is due to performance reasons. Though, that could change if I can make a benchmark (or someone else) that convinces me that a Pythonic …
=> Add CACHALOT_ONLY_CACHABLE_APPS & CACHALOT_UNCACHABLE_APPS (Fixes #186)

.github/workflows/ci.yml, README.rst, docs/quickstart.rst, setup.py, tox.ini
Drop Django 3.0 support
* Extended support for Django 3.0 was ended on April 6, 2021
=> Drop Django 3.0 support

CHANGELOG.rst, cachalot/tests/read.py, cachalot/utils.py
Fixes #193 
Ignore the PostgreSQL test cases. That is due to the psycopg2 package itself which is incompatible with Django 2.2.
=> Check for Uncachables (i.e. Now) in annotations

cachalot/tests/read.py, cachalot/utils.py
https://github.com/django/django/blob/f42ccdd835e5b3f0914b5e6f87621c648136ea36/django/db/models/expressions.py#L370
Handle **annotation** cases:
- when `Subquery` is part of the `When`
- when `Coalesce` is used
- when `RawSQL` is used
Expressions can contain multiple elements and all of them have to be checked.
Ensure that all elements are checked for queries.
=> Simplify annotation handling by using the flatten method:

cachalot/__init__.py
Django 3.2 default_app_config was deprecated since it's not needed
Deprecation
=> Fix Django 3.2 default_app_config deprecation

.github/workflows/ci.yml, CHANGELOG.rst, setup.py, tox.ini
fixes #205
Add Python 3.10 support
New version of Python! Currently, only Django 3.2 supports it.
=> Add Python 3.10 Support (fixes #205)

cachalot/monkey_patch.py
[//]: # (What are you proposing and how would we implement it?)
During our recent efforts to increase speed of our system we noticed that in some situations django-cachalot performs unnecessary table invalidations after SELECT SQL statements.
Many models in our system have DateTimeFields which track when model instance was created and updated. We name these fields "created_at" and "updated_at". When retrieving objects from the database, Django's ORM performs SELECT SQL statement behind the scenes  - e.g. for our models with "created_at" and "updated_at" DateTimeFields the statement will look like this:
`
'SELECT some_field_name, some_other_field_name, created_at, updated_at from some_table_name;'
`
This SELECT SQL statement should not invalidate "some_table_name" table, because SELECT SQL …
=> table invalidation condition enhanced

MANIFEST.in
[//]: Include docs in sdist
[//]: # Allow to include documentation in debian package
=> Include docs in sdist. Closes #201

MANIFEST.in
[//]: Add test settings to sdist
=> Add test settings to sdist. Closes #200.

docs/limits.rst
There is an outdated comment about a bug in the docs. I believe this adjustment can save a click for most people.
=> Adjusted bug reference in docs

CHANGELOG.rst, cachalot/tests/models.py, cachalot/tests/multi_db.py, cachalot/tests/read.py, cachalot/tests/test_utils.py, cachalot/tests/thread_safety.py, cachalot/tests/transaction.py, cachalot/tests/write.py, tox.ini
In addition to the changes @Andrew-Chen-Wang implemented, this additional work aims to correct the test issues his PR was experiencing.
- Updated tests to account for the `BEGIN` and `COMMIT` query changes in Django 4.2
- Standardized django version comparisons in tests
I have not been able to verify tests locally, but based this work on the tox output in CI. Once merged into [noripyt:andrew-wang/dj4.2](https://github.com/noripyt/django-cachalot/tree/andrew-wang/dj4.2) and run through CI again, I will happily clean up any remaining minor issues.
=> Correct problems with tests to get django-cachalot to work with 4.2

cachalot/utils.py
=> Fix cachalot.utils prior to db connection

cachalot/monkey_patch.py
Catch ModuleNotFoundError for error cases due to pickle serialization of old classpath
I propose a fix for the issue I wrote: https://github.com/noripyt/django-cachalot/issues/257
As for previous KeyError catching implementation, I don't know how to test it. Do you have any idea?
=> fix: Catch ModuleNotFoundError on cache retrieve

cachalot/tests/migrations/0001_initial.py, cachalot/tests/models.py, cachalot/tests/read.py, cachalot/utils.py
Fixes #218 
This should make queries that filter on enum values stop raising `UncachableQuery` by inferring their real type. See #218 for an example of a query that's fixed by this PR.
Cache everything? :)
=> Add support for caching queries with enum filters

cachalot/settings.py, docs/quickstart.rst, settings.py, tox.ini
Closes #209.
Closes #222.
Add support to the test matrix for testing against Django's built in redis cache backend.
Fewer dependencies :)
=> Add support for testing against the builtin redis backend
